-- Naming: pk_<table>, fk_<table>_<ref>, idx_<table>_<column(s)>; snake_case columns.

-- UUID generated by the domain, not the database: the id is known before the INSERT. DECIMAL, never FLOAT, for money.
CREATE TABLE orders
(
    id           UUID           NOT NULL,
    customer_id  VARCHAR(36)    NOT NULL,
    seller_id    VARCHAR(36)    NOT NULL,
    total_amount DECIMAL(19, 4) NOT NULL,
    -- VARCHAR, not CHAR: CHAR is blank-padded in PostgreSQL, which breaks equality comparisons.
    currency     VARCHAR(3)     NOT NULL,
    status       VARCHAR(20)    NOT NULL,
    -- TIMESTAMPTZ, not TIMESTAMP: independent of the JVM's default zone.
    placed_at    TIMESTAMPTZ    NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_orders_seller_id ON orders (seller_id);
CREATE INDEX idx_orders_status ON orders (status);

-- No primary key: @ElementCollection replaces the whole set on update, fine for a handful of rows
CREATE TABLE order_lines
(
    order_id            UUID           NOT NULL,
    product_id          VARCHAR(255)   NOT NULL,
    product_name        VARCHAR(500)   NOT NULL,
    quantity            INTEGER        NOT NULL CHECK (quantity >= 1),
    unit_price_amount   DECIMAL(19, 4) NOT NULL CHECK (unit_price_amount > 0),
    unit_price_currency VARCHAR(3)     NOT NULL,
    CONSTRAINT fk_order_lines_orders
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_lines_order_id ON order_lines (order_id);
